// Autogenerated from Pigeon (v2.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class LNCDComputationNotification;

@interface LNCDComputationNotification : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithTitle:(NSString *)title
    message:(NSString *)message
    percentProgress:(NSNumber *)percentProgress;
@property(nonatomic, copy) NSString * title;
@property(nonatomic, copy) NSString * message;
@property(nonatomic, strong) NSNumber * percentProgress;
@end

/// The codec used by LNCDNativeMainApi.
NSObject<FlutterMessageCodec> *LNCDNativeMainApiGetCodec(void);

@protocol LNCDNativeMainApi
- (void)startServiceNotification:(LNCDComputationNotification *)notification error:(FlutterError *_Nullable *_Nonnull)error;
- (void)stopServiceWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void LNCDNativeMainApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<LNCDNativeMainApi> *_Nullable api);

/// The codec used by LNCDNativeDialogApi.
NSObject<FlutterMessageCodec> *LNCDNativeDialogApiGetCodec(void);

@protocol LNCDNativeDialogApi
- (void)closeDialogWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void LNCDNativeDialogApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<LNCDNativeDialogApi> *_Nullable api);

/// The codec used by LNCDNativeBackgroundServiceApi.
NSObject<FlutterMessageCodec> *LNCDNativeBackgroundServiceApiGetCodec(void);

@protocol LNCDNativeBackgroundServiceApi
- (void)stopServiceWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)openDialogWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)updateNotificationNotification:(LNCDComputationNotification *)notification error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void LNCDNativeBackgroundServiceApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<LNCDNativeBackgroundServiceApi> *_Nullable api);

NS_ASSUME_NONNULL_END
